const today = new Date();

export let timelineResourceData: Object[] = [
    {
        Id: 1,
        CustomerName: "C_1",
        Subject: 'Appointment 1',
        Services: ['service_1', 'service_2'],
        StartTime: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 10, 0),
        EndTime: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 12, 30),
        TechnicianId: 1,
        Note: "Note 1",
    },
    {
        Id: 2,
        CustomerName: "C_2",
        Subject: 'Appointment 2',
        Services: ['service_1', 'service_2'],
        StartTime: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 9, 0),
        EndTime: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 10, 0),
        TechnicianId: 1,
        Note: "Note 1",
    },
    {
        Id: 3,
        CustomerName: "C_3",
        Subject: 'Appointment 3',
        Services: ['service_1', 'service_2'],
        StartTime: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 11, 0),
        EndTime: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 12, 0),
        TechnicianId: 1,
        Note: "Note 1",
    },
    {
        Id: 4,
        CustomerName: "C_4",
        Subject: 'Appointment 4',
        Services: ['service_1', 'service_2'],
        StartTime: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 14, 0),
        EndTime: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 15, 0),
        TechnicianId: 1,
        Note: "Note 2",
    },
];

export const technicianData = [
    { name: 'Alexandra Martinez', id: 1, color: '#ffaa00', description: "Example 1" },
    { name: 'Brandon Williams', id: 2, color: '#f8a398', description: "Example 2" },
    { name: 'Catherine Johnson', id: 3, color: '#7fa900', description: "Example 3" },
    { name: 'David Thompson', id: 4, color: '#7fa903', description: "Example 4" },
    { name: 'Emily Davis', id: 5, color: '#7fa920', description: "Example 5" },
    { name: 'Michael Anderson', id: 6, color: '#7fa960', description: "Example 6" },
];

export const servicesData = [
    { id: 1, name: "Manicure", type: "Manicure" },
    { id: 2, name: "Spa Manicure", type: "Manicure" },
    { id: 3, name: "Manicure Gel Color", type: "Manicure" },
    { id: 4, name: "Manicure French Gel", type: "Manicure" },
    { id: 5, name: "Acrylic Fullset", type: "Manicure" },
    { id: 6, name: "Fill Acrylic", type: "Manicure" },
    { id: 7, name: "Fullset Pink & White", type: "Manicure" },
    { id: 8, name: "Fill Pink & White", type: "Manicure" },
    { id: 9, name: "Polish Change Nails", type: "Manicure" },
    { id: 10, name: "Take Off Acrylic Nails", type: "Manicure" },
    { id: 11, name: "Nails Repair", type: "Manicure" },
    { id: 12, name: "Cut Down", type: "Manicure" },
    { id: 13, name: "Nails Design", type: "Manicure" },
    { id: 14, name: "Classic Pedicure", type: "Pedicure" },
    { id: 15, name: "Organic Spa", type: "Pedicure" },
    { id: 16, name: "Veosh", type: "Pedicure" },
    { id: 17, name: "Lavender", type: "Pedicure" },
    { id: 18, name: "Jasmine", type: "Pedicure" },
    { id: 19, name: "Cucumber", type: "Pedicure" },
    { id: 20, name: "Peppermint", type: "Pedicure" },
    { id: 21, name: "Ocean Refresh", type: "Pedicure" },
    { id: 22, name: "Green Tea", type: "Pedicure" },
    { id: 23, name: "Mango", type: "Pedicure" },
    { id: 24, name: "Tangerine", type: "Pedicure" },
    { id: 25, name: "Lemon", type: "Pedicure" },
    { id: 26, name: "Olive Sensation", type: "Pedicure" },
    { id: 27, name: "Polish Change Toes", type: "Pedicure" },
    { id: 28, name: "Eyebrows", type: "Waxing" },
    { id: 29, name: "Lip", type: "Waxing" },
    { id: 30, name: "Chin", type: "Waxing" },
    { id: 31, name: "Side Burns", type: "Waxing" },
    { id: 32, name: "Underarms", type: "Waxing" },
    { id: 33, name: "Bikini wax", type: "Waxing" },
    { id: 34, name: "Brazilian", type: "Waxing" },
    { id: 35, name: "Full Legs", type: "Waxing" },
    { id: 36, name: "Half Legs", type: "Waxing" },
    { id: 37, name: "Full Arms", type: "Waxing" },
    { id: 38, name: "Half Arms", type: "Waxing" },
    { id: 39, name: "Full Back", type: "Waxing" },
    { id: 40, name: "Half Back", type: "Waxing" },
    { id: 41, name: "Chest", type: "Waxing" },
    { id: 42, name: "Pedicure", type: "Children Services" },
    { id: 43, name: "Spa Pedicure", type: "Children Services" },
    { id: 44, name: "Manicure", type: "Children Services" },
    { id: 45, name: "Spa Manicure", type: "Children Services" },
    { id: 46, name: "Gel Manicure Kid", type: "Children Services" },
    { id: 47, name: "Gel Pedicure Kid", type: "Children Services" },
    { id: 48, name: "French Manicure", type: "Children Services" },
    { id: 49, name: "Polish Change Nails", type: "Children Services" },
    { id: 50, name: "Polish Change Toes", type: "Children Services" },
    { id: 51, name: "Dip Color", type: "Manicure" },
    { id: 52, name: "Spa Pedicure (Deluxe)", type: "Pedicure" },
    { id: 53, name: "Lavender Pedicure", type: "Pedicure" },
    { id: 54, name: "Eyebrows Tint", type: "Tint" },
    { id: 55, name: "Eyelash Tint", type: "Tint" }
];
